import mongoose from "mongoose";
import { Backlink, type IBacklink } from "../../models/Backlink.model";
import { DomainBacklinkStats } from "../../models/DomainBacklinkStats.model";
import { BacklinkAlert } from "../../models/BacklinkAlert.model";
import { AppError } from "../../utils/AppError";
import { normalizeDomain } from "../../utils/domain";
import { enqueueBacklinkSync } from "../../jobs/queues";
import { dataForSeoService } from "../../services/dataforseo.service";
import type { BacklinkQuery, CompetitorGapQuery, SyncBacklinksInput, UpdateBacklinkInput } from "./backlinks.validation";
import { Website } from "../../models/Website.model";

export const getBacklinks = async (userId: string, query: BacklinkQuery) => {
  const domain = normalizeDomain(query.domain);
  const filter: Record<string, unknown> = { userId, targetDomain: domain };

  if (query.status) {
    if (query.status === "active") filter.isLost = false;
    else if (query.status === "lost") filter.isLost = true;
    else if (query.status === "new") filter.isNewlyDiscovered = true;
    else if (query.status === "toxic") filter.toxicityStatus = "toxic";
    else if (query.status === "disavowed") filter.disavowed = true;
  }

  if (query.isDofollow) {
    filter.isDofollow = query.isDofollow === "true";
  }

  const sortOptions: Record<string, 1 | -1> = { [query.sort]: query.order === "asc" ? 1 : -1 };

  const [backlinks, total] = await Promise.all([
    Backlink.find(filter)
      .sort(sortOptions)
      .skip((query.page - 1) * query.limit)
      .limit(query.limit)
      .lean(),
    Backlink.countDocuments(filter),
  ]);

  return { backlinks, total, page: query.page, limit: query.limit };
};

export const updateBacklink = async (
  userId: string,
  backlinkId: string,
  input: UpdateBacklinkInput
): Promise<IBacklink> => {
  const backlink = await Backlink.findOne({ _id: backlinkId, userId });
  if (!backlink) throw new AppError("Backlink not found", 404);

  if (input.disavowed !== undefined) backlink.disavowed = input.disavowed;
  if (input.toxicityStatus !== undefined) backlink.toxicityStatus = input.toxicityStatus;

  await backlink.save();
  return backlink;
};

export const generateDisavowFile = async (userId: string, domain: string): Promise<string> => {
  const targetDomain = normalizeDomain(domain);
  const backlinks = await Backlink.find({ userId, targetDomain, disavowed: true }).lean();

  if (backlinks.length === 0) {
    throw new AppError("No disavowed backlinks found for this domain.", 404);
  }

  const lines = [
    `# Disavow file generated by AI SEO Rank Tracker for ${targetDomain}`,
    `# Generated on ${new Date().toISOString()}`,
    "",
  ];

  const domainsToDisavow = new Set<string>();
  const urlsToDisavow = new Set<string>();

  backlinks.forEach((bl) => {
    // If the whole domain is toxic/disavowed across multiple links, we might just disavow the domain.
    // For simplicity, we disavow specific URLs unless requested otherwise, but Google recommends domain:.
    // In a real app, users choose domain vs URL. Here we'll disavow the domain for maximum safety.
    domainsToDisavow.add(bl.domainFrom);
  });

  domainsToDisavow.forEach((d) => lines.push(`domain:${d}`));

  return lines.join("\n");
};

export const getBacklinkStats = async (userId: string, domain: string) => {
  const targetDomain = normalizeDomain(domain);
  
  const [latestStats, trend] = await Promise.all([
    DomainBacklinkStats.findOne({ userId, domain: targetDomain }).sort({ date: -1 }).lean(),
    DomainBacklinkStats.find({ userId, domain: targetDomain })
      .sort({ date: 1 })
      .limit(30)
      .lean(),
  ]);

  return { latestStats, trend };
};

export const enqueueSync = async (userId: string, input: SyncBacklinksInput) => {
  const targetDomain = normalizeDomain(input.domain);
  const website = await Website.findOne({ userId, domain: targetDomain });
  
  const job = await enqueueBacklinkSync({
    userId,
    websiteId: website?._id ? website._id.toString() : undefined,
    domain: targetDomain,
  });

  return { jobId: job.id };
};

export const syncBacklinksJob = async (
  userId: string,
  domain: string,
  websiteId?: string
) => {
  const targetDomain = normalizeDomain(domain);
  const [summary, rawBacklinks] = await Promise.all([
    dataForSeoService.getBacklinkSummary(targetDomain),
    dataForSeoService.getBacklinks(targetDomain, 500)
  ]);

  const date = new Date();
  date.setUTCHours(0, 0, 0, 0);

  // Mark all existing active backlinks as potentially lost
  await Backlink.updateMany(
    { userId, targetDomain, isLost: false },
    { $set: { isLost: true } }
  );

  let newLinks = 0;
  let lostLinks = 0; // will be calculated after

  const bulkWrites = rawBacklinks.map((bl) => {
    const toxicityScore = bl.backlink_spam_score || 0;
    const toxicityStatus: "safe" | "suspicious" | "toxic" = toxicityScore > 60 ? "toxic" : toxicityScore > 30 ? "suspicious" : "safe";

    return {
      updateOne: {
        filter: { userId: new mongoose.Types.ObjectId(userId), targetDomain, urlFrom: bl.url_from, urlTo: bl.url_to },
        update: {
          $set: {
            domainFrom: bl.domain_from,
            anchorText: bl.anchor,
            isDofollow: bl.dofollow,
            spamScore: bl.backlink_spam_score,
            domainRank: bl.domain_from_rank,
            pageRank: bl.rank,
            isLost: false, // It's in the latest sync, so it's not lost
            lastSeenAt: new Date(),
            toxicityScore,
            toxicityStatus,
          },
          $setOnInsert: {
            isNewlyDiscovered: true,
            firstSeenAt: new Date(bl.first_seen || new Date()),
            disavowed: false,
          }
        },
        upsert: true,
      }
    };
  });

  if (bulkWrites.length > 0) {
    const result = await Backlink.bulkWrite(bulkWrites, { ordered: false });
    newLinks = result.upsertedCount || 0;
  }

  const lostCount = await Backlink.countDocuments({ userId, targetDomain, isLost: true, updatedAt: { $gte: date } });

  const stats = await DomainBacklinkStats.findOneAndUpdate(
    { userId, domain: targetDomain, date },
    {
      $set: {
        websiteId,
        totalBacklinks: summary.total_backlinks,
        referringDomains: summary.referring_domains,
        dofollowBacklinks: summary.dofollow,
        domainRank: summary.rank,
        spamScore: summary.backlinks_spam_score,
        newBacklinks: newLinks,
        lostBacklinks: lostCount,
      }
    },
    { upsert: true, new: true }
  );

  // Generate alerts for new toxic links
  if (newLinks > 0) {
    const toxicLinks = await Backlink.find({ userId, targetDomain, isNewlyDiscovered: true, toxicityStatus: "toxic" }).lean();
    for (const link of toxicLinks) {
      await BacklinkAlert.create({
        userId,
        domain: targetDomain,
        type: "toxic_link",
        severity: "critical",
        message: `New toxic backlink detected from ${link.domainFrom} (Spam Score: ${link.spamScore})`,
        backlinkId: link._id,
      });
    }
  }

  // Generate alerts for lost high authority links
  if (lostCount > 0) {
    const lostHighDa = await Backlink.find({ userId, targetDomain, isLost: true, domainRank: { $gt: 40 }, updatedAt: { $gte: date } }).lean();
    for (const link of lostHighDa) {
      await BacklinkAlert.create({
        userId,
        domain: targetDomain,
        type: "lost_link",
        severity: "warning",
        message: `Lost high-authority backlink from ${link.domainFrom} (DA: ${link.domainRank})`,
        backlinkId: link._id,
      });
    }
  }

  // Clear isNewlyDiscovered flag for old links (older than 7 days)
  const sevenDaysAgo = new Date();
  sevenDaysAgo.setDate(sevenDaysAgo.getDate() - 7);
  await Backlink.updateMany(
    { userId, targetDomain, isNewlyDiscovered: true, firstSeenAt: { $lt: sevenDaysAgo } },
    { $set: { isNewlyDiscovered: false } }
  );

  return { imported: rawBacklinks.length, newLinks, lostCount };
};

export const getCompetitorGap = async (userId: string, query: CompetitorGapQuery) => {
  const targetDomain = normalizeDomain(query.domain);
  const competitors = query.competitors.map(normalizeDomain);

  // Get referring domains for competitors
  const competitorBacklinks = await Promise.all(
    competitors.map(async (comp) => {
      try {
        const bls = await dataForSeoService.getBacklinks(comp, 100);
        return { domain: comp, referringDomains: [...new Set(bls.map((b) => b.domain_from))] };
      } catch (e) {
        return { domain: comp, referringDomains: [] };
      }
    })
  );

  // Get referring domains for target
  const targetBacklinks = await Backlink.find({ userId, targetDomain, isLost: false }).distinct("domainFrom");

  // Find domains that link to at least one competitor but not to target
  const gapDomains = new Map<string, { domain: string, linkedCompetitors: string[], count: number }>();

  competitorBacklinks.forEach((comp) => {
    comp.referringDomains.forEach((refDomain) => {
      if (!targetBacklinks.includes(refDomain)) {
        if (!gapDomains.has(refDomain)) {
          gapDomains.set(refDomain, { domain: refDomain, linkedCompetitors: [], count: 0 });
        }
        const gap = gapDomains.get(refDomain)!;
        gap.linkedCompetitors.push(comp.domain);
        gap.count++;
      }
    });
  });

  // Sort by count of competitors linked (highest first)
  const opportunities = Array.from(gapDomains.values())
    .sort((a, b) => b.count - a.count)
    .slice(0, query.limit);

  return { opportunities };
};
